// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quaexlcelfiknbpgprdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1YWV4bGNlbGZpa25icGdwcmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjgzMjUsImV4cCI6MjA1ODgwNDMyNX0.oM_y_eTF04SyQLiiE6eqxk4Dku0hbFyWr36z_-T8IZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);